<?php
/**
 * Athene2 - Advanced Learning Resources Manager
 *
 * @author      Aeneas Rekkas (aeneas.rekkas@serlo.org)
 * @license   http://www.apache.org/licenses/LICENSE-2.0  Apache License 2.0
 * @link        https://github.com/serlo-org/athene2 for the canonical source repository
 * @copyright   Copyright (c) 2013 Gesellschaft für freie Bildung e.V. (http://www.open-education.eu/)
 */
echo $this->doctype();
?>
<!--[if lt IE 9 ]>
<html class="old-ie fuelux" lang="<?php echo $this->currentLanguage(); ?>"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!-->
<html class="fuelux" lang="<?php echo $this->currentLanguage(); ?>"> <!--<![endif]-->
<?php print $this->partial('layout/partials/head'); ?>
<body itemscope itemtype="http://schema.org/WebPage">
<div class="wrap has-navigation has-context">
    <?php echo $this->partial('layout/partials/header'); ?>

    <div id="page" class="container clearfix<?php echo (!empty($this->registry()->get('rnav')) ? ' has-sidebar' : '') ?>">
        <?php echo $this->partial('layout/partials/left-sidebar'); ?>
        <section class="main clearfix">
            <!-- Added this style to align it on the footer -->
            <div id="content-layout" style="position:relative;" class="content clearfix">
                <?php echo $this->partial('layout/partials/notifications'); ?>
                <?php echo $this->partial('layout/partials/main'); ?>
                <!-- move this to the bottom of the page -->
                <div style="border: red 1px solid; position:absolute;bottom:0;">
                    <span style="float:left;">Text about the question (-.-)...</span>
                    <div class="feedback-action" style="float:right;" data-user="{{ user().getAuthenticatedUserID() }}" data-object="{{ entity.getId() }}"></div>
                </div>
                <!-- move this to the bottom of the page END -->
            </div>
            <?php echo $this->partial('layout/partials/right-sidebar'); ?>
            <?php echo $this->horizon(3); ?>
        </section>
    </div>
    <div id="footer-push"></div>
</div>
<?php echo $this->partial('layout/partials/footer'); ?>
<?php echo $this->partial('layout/partials/default-modal'); ?>
<?php echo $this->placeholder('modals'); ?>
<?php echo $this->tracking(); ?>
<?php echo $this->partial('layout/partials/noscript'); ?>
</body>
</html>
